# Site settings
name: Adriana Sánchez
title: Adriana Sánchez | MSc. Data Scientist
description: I am a data expert and product architect. My passion lies in unearthing valuable insights from data and architecting state-of-the-art pipelines to fuel product innovation.
url: https://adriasg.github.io/
baseurl: ''
email: adrianasg.15@gmail.com
#cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: adrianasg.15@gmail.com
  - title: github
    url: https://github.com/AdriaSG
  - title: linkedin
    url: https://www.linkedin.com/in/adrianasanchezgar/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
